bundler_args: --without development
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby
script: "ruby -Itest:lib test/all.rb"
branches:
  only:
    - master
env: JRUBY_OPTS=--1.9
# RBXOPT=-X19 # need to sort out bundler/setup requiring issue
